apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-service
  labels:
    app: lab-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab-service
  template:
    metadata:
      labels:
        app: lab-service
    spec:
      containers:
        - name: lab-service
          image: cohad-lab-service:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /hello
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /hello
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
