apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-service
  labels:
    app: lab-service

spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab-service
  template:
    metadata:
      labels:
        app: lab-service
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: lab-config
      containers:
        - name: lab-service
          image: cohad-lab-service:v7
          imagePullPolicy: IfNotPresent
          env:
            # ConfigMap (V6)
            - name: APP_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: lab-config
                  key: APP_MESSAGE

            # Secret (V7)
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: lab-secrets
                  key: API_KEY

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lab-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: config-volume
              mountPath: /config
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
