apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-service
  namespace: mls-lab
  labels:
    app: lab-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab-service
  template:
    metadata:
      labels:
        app: lab-service
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: lab-config
      containers:
        - name: lab-service
          image: cohad-lab-service:v17
          imagePullPolicy: IfNotPresent

          env:
            # Secret (V7)
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: lab-secrets
                  key: API_KEY

            # âœ… DB creds come from Secret and are referenced by application.properties
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: lab-secrets
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lab-secrets
                  key: POSTGRES_PASSWORD

            # Profile & external config
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: lab-config
                  key: SPRING_PROFILES_ACTIVE

            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "file:/config/"

          volumeMounts:
            - name: config-volume
              mountPath: /config

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          ports:
            - containerPort: 8080

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
