apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migration
  namespace: mls-lab
spec:
  template:
    spec:
      containers:
        - name: flyway
          image: cohad-lab-service:v17
          command: ["java", "-jar", "app.jar"]
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: lab-secrets
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lab-secrets
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: lab-secrets
                  key: POSTGRES_DB
      restartPolicy: Never
  backoffLimit: 2
