apiVersion: v1
kind: Secret
metadata:
  name: lab-secrets
  namespace: mls-lab
type: Opaque
stringData:
  API_KEY: dummy-api-key
  POSTGRES_DB: labdb
  POSTGRES_USER: labuser
  POSTGRES_PASSWORD: labpass