apiVersion: v1
kind: Service
metadata:
  name: lab-service
  namespace: mls-lab
spec:
  selector:
    app: lab-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
